import './globals.css';
import {Providers} from './providers'
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/index';


export const metadata = {
  title: '',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Navbar />
            {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
